apiVersion: apps/v1
kind: Deployment
metadata:
  name: balkfet-webui
  namespace: balkfet-prod
  labels:
    app: balkfet-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balkfet-webui
  template:
    metadata:
      labels:
        app: balkfet-webui
    spec:
      containers:
      - name: balkfet-webui
        image: ghcr.io/z3r0esc/gde-balkfet-beadando/webui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: balkfet-webui
  namespace: balkfet-prod
spec:
  selector:
    app: balkfet-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
